# go hub binary
FROM golang:alpine as go
RUN apk --update add --no-scripts ca-certificates git
RUN go install github.com/github/hub@latest

# python yq binary
FROM six8/pyinstaller-alpine:alpine-3.6-pyinstaller-v3.4 as yq
ARG YQ_VERSION=2.10.0
ENV PATH="/pyinstaller:$PATH"
RUN pip install yq==${YQ_VERSION}
RUN pyinstaller --noconfirm --onefile --log-level DEBUG --clean --distpath /tmp/ $(which yq)

# kubectl binary
FROM bitnamilegacy/kubectl:1.33.1 as kubectl

# Main
FROM node:22.21.0-trixie-slim
RUN apt update \
    && apt -y install \
    bash \
    busybox \
    ca-certificates \
    curl \
    git \
    jq \
    && ln -s /bin/busybox /usr/bin/[[
RUN npm upgrade -g npm
COPY --from=go /go/bin/hub /usr/local/bin/hub
COPY --from=yq /tmp/yq /usr/local/bin/yq
COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/
WORKDIR /cf-cli
COPY package.json yarn.lock check-version.js run-check-version.js /cf-cli/
RUN yarn install --prod --frozen-lockfile && \
    yarn cache clean
COPY . /cf-cli
RUN yarn generate-completion
RUN ln -s $(pwd)/lib/interface/cli/codefresh /usr/local/bin/codefresh
RUN codefresh components update --location components
# we keep /root as home directory because cli by default looks for $HOME/.cfconfig
# and we do not want to break user automation if they used to bind their .cfconfig
# to the /root/.cfconfig
RUN useradd -m -d /root -s /bin/sh cfu \
   && chown -R $(id -g cfu) /root /cf-cli \
   && chgrp -R $(id -g cfu) /root /cf-cli \
   && chmod -R g+rwX /root

# Node.js warnings must be suppressed to ensure that automations relying on exact output are not disrupted
ENV NODE_NO_WARNINGS=1
USER cfu
ENTRYPOINT ["codefresh"]
