name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail. What did you expect to happen? What actually happened?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of the CLI are you running?
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: Please copy and paste any additional information we can use to reproduce the bug.
      render: shell
