#!/usr/bin/env node

const Output = require('../../output/Output');

process.on('uncaughtException', (err) => {
    Output.printError(err);
    process.exit(1);
});

process.on('unhandledRejection', (err) => {
    Output.printError(err);
    process.exit(1);
});

if (process.argv.includes('--get-yargs-completions')) {
    const completionInterface = require('./completion');
    completionInterface().argv; // eslint-disable-line
} else {
    const commandLineInterface = require('./commad-line-interface');
    commandLineInterface().catch((err) => {
        Output.printError(err);
        process.exit(1);
    });
}

